name: json2dart_serialization
description: 一个网页版本的json转dart库
# version: 1.0.0
#homepage: https://www.example.com
#author: Caijinglong <email@example.com>

environment:
  sdk: ">=2.14.0 <3.0.0"

#dependencies:
#  path: ^1.4.1
dependencies:
  # Your other regular dependencies here
  json_annotation: ^4.3.0
  intl: ^0.15.8

dev_dependencies:
  build_web_compilers: ^3.2.1
  json_serializable: ^6.0.1
  build_runner: ^2.1.4
